version: '2.3'
services:
 elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
   container_name: elasticsearch-Kata
   runtime: kata-runtime 
   mem_limit: 1G
   environment:
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
   restart: always
   ulimits:
    memlock:
     soft: -1
     hard: -1
   volumes:
     - ./data/influxdb:/data
   ports:
     - 9201:9200
 elasticsearch-default:
   image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
   container_name: elasticsearch
   environment:
     - bootstrap.memory_lock=true
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
   restart: always
   ulimits:
     memlock:
      soft: -1
      hard: -1
   volumes:    
      - ./data/influxdb:/data
   ports:
     - 9200:9200
 influxdb:
  image: tutum/influxdb:0.9
  restart: always
  environment:
   - PRE_CREATE_DB=cadvisor
  ports:
   - "8083:8083"
   - "8086:8086"
  expose:
   - "8090"
   - "8099"
  volumes_from:
   - "elasticsearch"
   - "elasticsearch-default"
 cadvisor:
  image: google/cadvisor:v0.29.0
  links:
    - influxdb:influxsrv
  command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxsrv:8086
  restart: always
  ports:
   - "8091:8080"
  volumes:       
   - /:/rootfs:ro
   - /var/run:/var/run:rw
   - /sys:/sys:ro
   - /var/lib/docker/:/var/lib/docker:ro
  depends_on:
    - elasticsearch
    - elasticsearch-default
 grafana:
   image: grafana/grafana:2.6.0
   restart: always
   links:
    - influxdb:influxsrv
   ports:
    - "3000:3000"
   environment:
    - HTTP_USER=admin
    - HTTP_PASS=admin
    - INFLUXDB_HOST=influxsrv
    - INFLUXDB_PORT=8086
    - INFLUXDB_NAME=cadvisor
    - INFLUXDB_USER=root
    - INFLUXDB_PASS=root
